apiVersion: v1
kind: Service
metadata:
  name: fetcher
  labels:
    app: fetcher
spec:
  ports:
  - port: 50052
  selector:
    app: fetcher
    tier: app
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher
  labels:
    app: fetcher
spec:
  selector:
    matchLabels:
      app: fetcher
      tier: app
  template:
    metadata:
      labels:
        app: fetcher
        tier: app
    spec:
      containers:
      - image: hatena-intern-2020-fetcher
        imagePullPolicy: Never
        name: fetcher
        env:
        - name: GRPC_PORT
          value: "50052"
        envFrom:
        - configMapRef:
            name: fetcher-app-env-vars
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 50052
          name: fetcher
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50052", "-connect-timeout=5s", "-rpc-timeout=5s"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50052", "-connect-timeout=5s", "-rpc-timeout=5s"]
          initialDelaySeconds: 10
        securityContext:
          runAsNonRoot: true
          capabilities:
            drop:
            - all
            add:
            - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
